import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const notoSansJp = Noto_Sans_JP({
    variable: "--font-noto-sans-jp",
    subsets: ["latin"], // You might want to include "japanese" if needed
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ja">
            <body className={`${notoSansJp.variable}  antialiased`}>
                {children}
            </body>
        </html>
    );
}
